; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = addone-esp32dev

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions/addone_ota.csv
lib_deps = 
	bblanchon/ArduinoJson@^6.21.5
	adafruit/RTClib@^2.1.4
	fastled/FastLED@^3.6.0
	knolleary/PubSubClient@^2.8
build_flags = 
	-D CORE_DEBUG_LEVEL=0

[env:addone-esp32dev]
build_flags = 
	${env.build_flags}
	-D ADDONE_CONFIG_PROFILE_LOCAL=1

[env:addone-esp32dev-beta]
build_flags = 
	${env.build_flags}
	-D ADDONE_CONFIG_PROFILE_BETA=1

[env:addone-esp32dev-beta-ota-base]
build_flags =
	${env:addone-esp32dev-beta.build_flags}
	-D ADDONE_FIRMWARE_VERSION=\"2.0.0-beta.1\"

[env:addone-esp32dev-beta-ota-proof]
extends = env:addone-esp32dev-beta-ota-base
build_flags =
	${env:addone-esp32dev-beta.build_flags}
	-D ADDONE_FIRMWARE_VERSION=\"2.0.0-beta.14\"
